# Taken from https://github.com/craigcitro/r-travis and
# modified after looking at
# https://github.com/hadley/adv-r/blob/master/.travis.yml
# and https://github.com/rmflight/categoryCompare/blob/master/.travis.yml

## Not finished. Look also at https://github.com/yihui/knitr-examples/blob/master/Makefile

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  
install:
   - ./travis-tool.sh r_binary_install car
   - ./travis-tool.sh r_install knitr
   - ./travis-tool.sh github_package yihui/knitr
   - ./travis-tool.sh bioc_install limma
#  - ./travis-tool.sh install_deps

# script: ./travis-tool.sh run_tests
script:
   - Rscript -e 'library(knitr); knit("R-bioinfo-intro.Rnw")'
   - texi2pdf R-bioinfo-intro.tex   


after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
